.PHONY: clean All

All:
	@echo "----------Building project:[ IRCBot - Debug ]----------"
	@cd "IRCBot" && "$(MAKE)" -f  "IRCBot.mk"
clean:
	@echo "----------Cleaning project:[ IRCBot - Debug ]----------"
	@cd "IRCBot" && "$(MAKE)" -f  "IRCBot.mk" clean
